export const FETCH_ROOMS_DATA ='fetch_rooms_data';
export const PUT_ROOMS_DATA = 'put_rooms_data'; 
export const DELETE_ROOM = "delete_room";
export const ADD_ROOM = "add_room";
export const SEARCH_ROOMS_DATA = "search_rooms_data";
export const SEARCH_ROOMS = "search_rooms"; //za pretragu soba, bez filriranja
export const EDIT_ROOM = "edit_room";
export const PUT_IS_FETCH_ROOMS = "put_is_fetch_rooms";
export const PUT_PAGE_COUNT = "put_page_count";