language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules
    
script:
  - npm install -g serve
  - npm run build

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: centersystemfrontend
