export const FETCH_DOCTORS_DATA = 'fetch_doctors_data';//1.sa back na front pa put koja stavlja u store
export const PUT_DOCTOR_DATA = 'put_doctor';
export const ADD_DOCTOR = 'add_doctor';
export const FETCH_CADMIN_DATA = 'fetch_cadmin_data';
export const PUT_CADMIN_DATA = 'put_cadmin_data';
export const PUT_APPOINTMENT_TYPES = 'put_appointment_types';
export const FETCH_APPOINTMENT_TYPE = 'fetch_appointment_type';
export const ADD_APPOINTMENT_TYPE = 'add_appointment_type';
/*export const DELETE_DOCTOR = 'delete_doctor';
export const SEARCH_DOCTOR = 'search_doctor';
export const FETCH_ROOMS_DATA ='fetch_rooms_data';//preuzima sa backa podatke na front
export const PUT_ROOMS_DATA = 'put_rooms_data'; //preuzete podatke sa backa stavlja u store
export const DELETE_ROOMS_DATA = "delete_rooms_data";
export const ADD_ROOMS_DATA = "add_rooms_data";
export const SEARCH_ROOMS_DATA = "search_rooms_data";
export const EDIT_ROOMS_DATA = "edit_rooms_data";
export const FETCH_APPOINTMENT_TYPE = "fetch_appointment_type";
export const PUT_APPOINTMENT_TYPE = "put_appointment_type";
export const DELETE_APPOINTMENT_TYPE = "delete_appointment_data";
export const SEARCH_APPOINTMENT_TYPE="search_appointment_type";
export const EDIT_APPOINTMENT_TYPE = "edit_appointment_type";
export const ADD_APPOINTMENT_TYPE = "add_appointment_type";
export const PUT_DOCTORS_DATA = 'put_doctors_data';
*/
